### ISSUE TITLE
Glow chalk has weird lighting bug with doors

### ISSUE THREAD

**Issue by EGOIST1372** [DaFuqs/Chalk#12]
glow chalk has weird lighting bug with doors
the top half of the iron door seems weird
with glow chalk nearby
![image](https://user-images.githubusercontent.com/86555131/154821165-5f281ac1-b1fa-4cbf-ae94-8a419feec95f.png)
without glow chalk nearby
![image](https://user-images.githubusercontent.com/86555131/154821200-b4b077b1-86da-4ad1-94f3-5808cb083ef2.png)

**Comment by DaFuqs** [comment]
fixed

**Comment by EGOIST1372** [comment]
thank you so much

**Comment by EGOIST1372** [comment]
the bug is still there
![image](https://user-images.githubusercontent.com/86555131/154874770-8b030429-1cfe-4120-b572-d9137b977724.png)
